[package]
name = "monte_carlo_simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
statrs = "0.18.0"
rand = "0.9.2"
rand_distr = "0.5.1"
thiserror = "2.0.16"
anyhow = "1.0.99"
plotly = "0.13.5"